version: "3.9"
services:
    mysql:
        image: mysql
        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"
        networks:
            - testing-network
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_RANDOM_ROOT_PASSWORD: true
    mongo:
        image: mongo
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        networks:
            - testing-network
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    pg:
        image: postgres
        ports:
            - "${POSTGRESS_PORT}:${POSTGRESS_PORT}"
        networks:
            - testing-network
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}

    cassandra:
        image: cassandra:5.0
        ports:
            - ${CASSANDRA_PORT}:${CASSANDRA_PORT}
        networks:
            - testing-network
        environment:
            - CASSANDRA_USER=${CASSANDRA_USERNAME}
            - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
            - MAX_HEAP_SIZE=256M
            - HEAP_NEWSIZE=100M
        volumes:
            - ./tests/cassandra.yaml:/etc/cassandra/cassandra.yaml
networks:
    testing-network:
